plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    kotlin("plugin.compose")
    id("org.jetbrains.compose")
}

dependencies {
    implementation(project(":shared"))
    
    // Compose for Desktop
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    
    // Ktor Client
    implementation("io.ktor:ktor-client-core:3.0.1")
    implementation("io.ktor:ktor-client-cio:3.0.1")
    implementation("io.ktor:ktor-client-websockets:3.0.1")
    implementation("io.ktor:ktor-client-content-negotiation:3.0.1")
    implementation("io.ktor:ktor-serialization-kotlinx-json:3.0.1")
    
    // Koin
    implementation("io.insert-koin:koin-core:3.5.6")
    
    // Serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")
    
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.8.0")
    
    // Opus codec (pure Java)
    implementation("io.github.jaredmdobson:concentus:1.0.1")

    // Logging
    implementation("ch.qos.logback:logback-classic:1.4.14")
    implementation("io.github.oshai:kotlin-logging-jvm:6.0.3")
}

kotlin {
    // Use Java 21 as requested
    jvmToolchain(21)
}

compose.desktop {
    application {
        mainClass = "com.voicechat.client.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb
            )
            packageName = "VoiceChat"
            packageVersion = "1.0.0"
        }
    }
}

// Copy native libs produced by :webrtc-native into this project's build dir and add to java.library.path for run
val copyNativeLibs by tasks.registering(Copy::class) {
    description = "Copy native libs from the webrtc-native module into this project's build/native-libs"
    val nativeSrc = project(":webrtc-native").layout.buildDirectory.dir("lib/main/debug")
    from(nativeSrc)
    into(layout.buildDirectory.dir("native-libs"))
}

// Ensure the native module is assembled before copying
copyNativeLibs.configure {
    dependsOn( ":webrtc-native:assemble" )
}

// Configure the run task to include the native-libs dir on java.library.path
// Configure JavaExec run tasks (if present) to include native dir on java.library.path
tasks.withType(org.gradle.api.tasks.JavaExec::class.java).matching { it.name == "run" }.configureEach {
    dependsOn(copyNativeLibs)
    doFirst {
        val nativeDir = layout.buildDirectory.dir("native-libs").get().asFile.absolutePath
        // append to existing jvmArgs
        val exec = this
        exec as org.gradle.api.tasks.JavaExec
        exec.jvmArgs = (exec.jvmArgs ?: listOf()) + listOf("-Djava.library.path=$nativeDir")
    }
}

// Small JavaExec task to run a native smoke-test main that calls the JNI stubs.
tasks.register("testNative", org.gradle.api.tasks.JavaExec::class.java) {
    group = "verification"
    description = "Run a small native smoke test that exercises JNI stubs (headless)."
    dependsOn(copyNativeLibs, "classes")
    // set the main class generated by Kotlin for the TestNativeMain.kt top-level main()
    mainClass.set("com.voicechat.client.native.TestNativeMainKt")
    // runtime classpath
    val mainSourceSet = project.extensions.getByName("sourceSets") as org.gradle.api.tasks.SourceSetContainer
    classpath = mainSourceSet.getByName("main").runtimeClasspath
    doFirst {
        val nativeDir = layout.buildDirectory.dir("native-libs").get().asFile.absolutePath
        jvmArgs = (jvmArgs ?: listOf()) + listOf("-Djava.library.path=$nativeDir")
    }
}
